services:

  neo4j-tp:
    image: neo4j:5.24
    container_name: neo4j-tp
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/anfneo4j2026
    volumes:
      - neo4j-tp-data:/data
      - neo4j-tp-logs:/logs
    networks:
      - datalab

  
volumes:
  neo4j-tp-data:
  neo4j-tp-logs:
